# update-tag.yml
- name: Update image tag in Kubernetes deployment file
  hosts: localhost
  vars:
    new_tag: "latest"  # default if not passed
    file_path: "k8s/app.yml"
  tasks:
    - name: Replace image tag with the new tag
      replace:
        path: "{{ file_path }}"
        regexp: 'image:\s+(.+):[^\s]+'
        replace: 'image: \1:{{ new_tag }}'
